export const languages = [
  "af",
  "am",
  "ar",
  "az",
  "be",
  "bg",
  "bn",
  "bs",
  "ca",
  "co",
  "cs",
  "cy",
  "da",
  "de",
  "el",
  "en",
  "eo",
  "es",
  "et",
  "eu",
  "fa",
  "fi",
  "fr",
  "fy",
  "ga",
  "gd",
  "gl",
  "gu",
  "ha",
  "he",
  "hi",
  "hr",
  "ht",
  "hu",
  "hy",
  "id",
  "ig",
  "is",
  "it",
  "ja",
  "jv",
  "ka",
  "kk",
  "km",
  "kn",
  "ko",
  "ku",
  "ky",
  "la",
  "lb",
  "lo",
  "lt",
  "lv",
  "mg",
  "mi",
  "mk",
  "ml",
  "mn",
  "mr",
  "ms",
  "mt",
  "my",
  "nb",
  "ne",
  "nl",
  "no",
  "ny",
  "or",
  "pa",
  "pl",
  "ps",
  "pt",
  "ro",
  "ru",
  "rw",
  "sd",
  "si",
  "sk",
  "sl",
  "sm",
  "sn",
  "so",
  "sq",
  "sr",
  "st",
  "su",
  "sv",
  "sw",
  "ta",
  "te",
  "tg",
  "th",
  "tk",
  "tl",
  "tr",
  "tt",
  "ug",
  "uk",
  "ur",
  "uz",
  "vi",
  "xh",
  "yi",
  "yo",
  "zh",
  "zu",
] as const;

// https://docs.google.com/spreadsheets/d/1M9sIYpFBAt1qLJXxbrT-AiMy_xHbq1r_bQux9m49FQQ/edit?usp=sharing
export const multilingualHellos = [
  {
    af: "Alexander die Grote",
    am: "ታላቁ እስክንድር",
    ar: "الإسكندر الأكبر",
    az: "Makedoniyalı İskəndər",
    be: "Аляксандр Македонскі",
    bg: "Александър Велики",
    bn: "আলেকজান্ডার দ্য গ্রেট",
    bs: "aleksandar veliki",
    ca: "Alexandre el Gran",
    co: "Lisandru Magnu",
    cs: "Alexandr Veliký",
    cy: "Alecsander Fawr",
    da: "Alexander den Store",
    de: "Alexander der Große",
    el: "Μέγας Αλέξανδρος",
    en: "Alexander the Great",
    eo: "Aleksandro la Granda",
    es: "Alejandro el Grande",
    et: "Aleksander Suur",
    eu: "Alexandro Handia",
    fa: "اسکندر کبیر",
    fi: "Aleksanteri Suuri",
    fr: "Alexandre le Grand",
    fy: "Alexander de grutte",
    ga: "Alastar Mór",
    gd: "Alasdair Mòr",
    gl: "Alexandre Magno",
    gu: "મહાન અલેકઝાન્ડર",
    ha: "Alexander the Great",
    he: "אלכסנדר הגדול",
    hi: "सिकंदर महान",
    hr: "Aleksandar Veliki",
    ht: "Aleksann Legran",
    hu: "Nagy Sándor",
    hy: "Ալեքսանդր Մակեդոնացին",
    id: "Alexander yang Agung",
    ig: "Alexander Onye Ukwu",
    is: "Alexander mikli",
    it: "Alessandro Magno",
    ja: "アレキサンダー大王",
    jv: "Alexander Agung",
    ka: "ალექსანდრე დიდი",
    kk: "Александр Македонский",
    km: "លោក Alexander ដ៏​អស្ចារ្យ",
    kn: "ಅಲೆಕ್ಸಾಂಡರ್ ದಿ ಗ್ರೇಟ್",
    ko: "알렉산더 대왕",
    ku: "Îskenderê Mezin",
    ky: "Улуу Александр",
    la: "Alexander Magnus",
    lb: "Alexander de Groussen",
    lo: "Alexander the Great",
    lt: "Aleksandras Didysis",
    lv: "Aleksandrs Lielais",
    mg: "Alexander the Great",
    mi: "Alexander the Great",
    mk: "Александар Велики",
    ml: "മഹാനായ അലക്സാണ്ടർ",
    mn: "Их Александр",
    mr: "अलेक्झांडर द ग्रेट",
    ms: "Alexander the Great",
    mt: "Alessandru l-Kbir",
    my: "မဟာအလက်ဇန်းဒါး",
    nb: "Alexander den store",
    ne: "अलेक्जेन्डर महान्",
    nl: "Alexander de Grote",
    no: "Alexander den store",
    ny: "Alexander Wamkulu",
    or: "ଆଲେକ୍ସଜାଣ୍ଡାର୍ ଦି ଗ୍ରେଟ୍ |",
    pa: "ਸਿਕੰਦਰ ਮਹਾਨ",
    pl: "Aleksander Wielki",
    ps: "سکندر اعظم",
    pt: "Alexandre o grande",
    ro: "Alexandru cel Mare",
    ru: "Александр Великий",
    rw: "Alegizandere Mukuru",
    sd: "سڪندر اعظم",
    si: "මහා ඇලෙක්සැන්ඩර්",
    sk: "Alexander Veľký",
    sl: "Aleksander Veliki",
    sm: "Alesana le Sili",
    sn: "Alexander Mukuru",
    so: "Alexander the Great",
    sq: "Aleksandri i Madh",
    sr: "Александар Велики",
    st: "Alexander e Moholo",
    su: "Alexander Agung",
    sv: "Alexander den store",
    sw: "Alexander Mkuu",
    ta: "மாவீரன் அலெக்ஸ்சாண்டர்",
    te: "అలెగ్జాండర్ ది గ్రేట్",
    tg: "Искандари Мақдунӣ",
    th: "อเล็กซานเดอร์มหาราช",
    tk: "Aleksandr Makedonskiý",
    tl: "Alexander the Great",
    tr: "Büyük İskender",
    tt: "Бөек Александр",
    ug: "ئىسكەندەر زۇلقەرنەيىن",
    uk: "Олександр Великий",
    ur: "سکندر اعظم",
    uz: "Iskandar Zulqarnayn",
    vi: "Alexander vĩ đại",
    xh: "UAlexander Omkhulu",
    yi: "אלעקסאנדער דער גרויסער",
    yo: "Alexander Nla",
    zh: "亚历山大大帝",
    zu: "Alexander Omkhulu",
  },
  {
    af: "Verenigde Koninkryk",
    am: "የተባበሩት የንጉሥ ግዛት",
    ar: "المملكة المتحدة",
    az: "Birləşmiş Krallıq",
    be: "Злучанае Каралеўства",
    bg: "Великобритания",
    bn: "যুক্তরাজ্য",
    bs: "ujedinjeno kraljevstvo",
    ca: "Regne Unit",
    co: "Regnu Unitu",
    cs: "Spojené království",
    cy: "Deyrnas Unedig",
    da: "Det Forenede Kongerige",
    de: "Großbritannien",
    el: "Ηνωμένο Βασίλειο",
    en: "United Kingdom",
    eo: "Unuiĝinta Reĝlando",
    es: "Reino Unido",
    et: "Ühendkuningriik",
    eu: "Erresuma Batua",
    fa: "انگلستان",
    fi: "Yhdistynyt kuningaskunta",
    fr: "Royaume-Uni",
    fy: "Feriene Keninkryk",
    ga: "an Ríocht Aontaithe",
    gd: "An Rìoghachd Aonaichte",
    gl: "Reino Unido",
    gu: "યુનાઇટેડ કિંગડમ",
    ha: "Ƙasar Ingila",
    he: "הממלכה המאוחדת",
    hi: "यूनाइटेड किंगडम",
    hr: "Ujedinjeno Kraljevstvo",
    ht: "Wayòm Ini",
    hu: "Egyesült Királyság",
    hy: "Միացյալ թագավորություն",
    id: "Britania Raya",
    ig: "United Kingdom",
    is: "Bretland",
    it: "Regno Unito",
    ja: "イギリス",
    jv: "Inggris",
    ka: "გაერთიანებული სამეფო",
    kk: "Біріккен корольдігі",
    km: "ចក្រភពអង់គ្លេស",
    kn: "ಯುನೈಟೆಡ್ ಕಿಂಗ್ಡಮ್",
    ko: "영국",
    ku: "Inglîz",
    ky: "Бириккен королдук",
    la: "regnum Unitum",
    lb: "Vereenegt Kinnekräich",
    lo: "ສະຫະລາຊະອານາຈັກ",
    lt: "Jungtinė Karalystė",
    lv: "Apvienotā Karaliste",
    mg: "fanjakana mitambatra",
    mi: "United Kingdom",
    mk: "Обединето Кралство",
    ml: "യുണൈറ്റഡ് കിംഗ്ഡം",
    mn: "Их Британи",
    mr: "युनायटेड किंगडम",
    ms: "United Kingdom",
    mt: "Ir-Renju Unit",
    my: "ယူနိုက်တက်ကင်းဒမ်း",
    nb: "Storbritannia",
    ne: "युनाइटेड किंगडम",
    nl: "Verenigd Koninkrijk",
    no: "Storbritannia",
    ny: "United Kingdom",
    or: "ଇଂଗଲାଣ୍ଡ୍",
    pa: "ਯੁਨਾਇਟੇਡ ਕਿਂਗਡਮ",
    pl: "Zjednoczone Królestwo",
    ps: "انګلستان",
    pt: "Reino Unido",
    ro: "Regatul Unit",
    ru: "Великобритания",
    rw: "Ubwongereza",
    sd: "برطانيه",
    si: "එක්සත් රාජධානිය",
    sk: "Spojene kralovstvo",
    sl: "Združeno kraljestvo",
    sm: "Malo tupu",
    sn: "Nyika dzakabatana",
    so: "Boqortooyada Ingiriiska",
    sq: "Mbretëria e Bashkuar",
    sr: "Велика Британија",
    st: "united kingdom",
    su: "karajaan Inggris",
    sv: "Storbritannien",
    sw: "Uingereza",
    ta: "ஐக்கிய இராச்சியம்",
    te: "యునైటెడ్ కింగ్‌డమ్",
    tg: "Инглистон",
    th: "ประเทศอังกฤษ",
    tk: "Angliýa",
    tl: "United Kingdom",
    tr: "Birleşik Krallık",
    tt: "Берләшкән Корольлек",
    ug: "United Kingdom",
    uk: "Об'єднане Королівство",
    ur: "متحدہ سلطنت یونائیٹڈ کنگڈم",
    uz: "Birlashgan Qirollik",
    vi: "Vương quốc Anh",
    xh: "Iunited kingdom",
    yi: "פֿאַראייניקטע מלכות",
    yo: "apapọ ijọba gẹẹsi",
    zh: "英国",
    zu: "i-United Kingdom",
  },
  {
    af: "Op soek na verlore tyd",
    am: "የጠፋውን ጊዜ በመፈለግ ላይ",
    ar: "بحثاً عن الزمن الضائع",
    az: "İtirilmiş Zamanın Axtarışında",
    be: "У пошуках страчанага часу",
    bg: "В търсене на изгубеното време",
    bn: "হারিয়ে যাওয়া সময়ের সন্ধানে",
    bs: "U potrazi za izgubljenim vremenom",
    ca: "A la recerca del temps perdut",
    co: "À a ricerca di u tempu persu",
    cs: "Hledání ztraceného času",
    cy: "Chwilio am Amser Coll",
    da: "På jagt efter den tabte tid",
    de: "Auf der Suche nach der verlorenen Zeit",
    el: "Σε αναζήτηση του χαμένου χρόνου",
    en: "In Search of Lost Time",
    eo: "En Serĉo de Perdita Tempo",
    es: "En busca del tiempo perdido",
    et: "Kaotatud aja otsinguil",
    eu: "Denbora galduaren bila",
    fa: "در جستجوی زمان از دست رفته",
    fi: "Kadonnutta aikaa etsimässä",
    fr: "À la recherche du temps perdu",
    fy: "Op syk nei ferlerne tiid",
    ga: "Ar Lorg Am Caillte",
    gd: "Ann an Lorg Ùine Caillte",
    gl: "Na procura do tempo perdido",
    gu: "ખોવાયેલા સમયની શોધમાં",
    ha: "A cikin Neman Bataccen Lokaci",
    he: "בחיפוש אחר זמן אבוד",
    hi: "खोए हुए समय की तलाश में",
    hr: "U potrazi za izgubljenim vremenom",
    ht: "Nan rechèch nan tan pèdi",
    hu: "Az elveszett idő nyomában",
    hy: "Կորցրած ժամանակի որոնման մեջ",
    id: "Mencari Waktu yang Hilang",
    ig: "N'ịchọ oge efu",
    is: "Í leit að týndum tíma",
    it: "Alla ricerca del tempo perduto",
    ja: "失われた時を求めて",
    jv: "Ing Search of Lost Time",
    ka: "დაკარგული დროის ძიებაში",
    kk: "Жоғалған уақытты іздеуде",
    km: "ក្នុងការស្វែងរកពេលវេលាដែលបាត់បង់",
    kn: "ಕಳೆದುಹೋದ ಸಮಯದ ಹುಡುಕಾಟದಲ್ಲಿ",
    ko: "잃어버린 시간을 찾아서",
    ku: "Di Lêgerîna Dema Wendakirî de",
    ky: "Жоголгон убакытты издөө",
    la: "In Search of Lost Tempus",
    lb: "Op der Sich no verluerener Zäit",
    lo: "ໃນການຊອກຫາເວລາທີ່ສູນເສຍໄປ",
    lt: "Prarasto laiko beieškant",
    lv: "Pazudušā laika meklējumos",
    mg: "Mitady fotoana very",
    mi: "Kei te rapu i te wa ngaro",
    mk: "Во потрага по изгубеното време",
    ml: "നഷ്ടപ്പെട്ട സമയം തേടി",
    mn: "Алдагдсан цаг хугацааны эрэлд",
    mr: "हरवलेल्या वेळेच्या शोधात",
    ms: "Dalam Mencari Masa Yang Hilang",
    mt: "Fit Fittex Żmien Mitluf",
    my: "ပျောက်ဆုံးသွားသောအချိန်ကိုရှာဖွေခြင်း။",
    nb: "På jakt etter tapt tid",
    ne: "हराएको समयको खोजीमा",
    nl: "Op zoek naar verloren tijd",
    no: "På jakt etter tapt tid",
    ny: "Kufunafuna Nthawi Yotayika",
    or: "ହଜିଯାଇଥିବା ସମୟର ସନ୍ଧାନରେ |",
    pa: "ਗੁਆਚੇ ਸਮੇਂ ਦੀ ਖੋਜ ਵਿੱਚ",
    pl: "W poszukiwaniu straconego czasu",
    ps: "د ورک شوي وخت په لټه کې",
    pt: "Em busca do tempo perdido",
    ro: "În căutarea timpului pierdut",
    ru: "В поисках утраченного времени",
    rw: "Mugushakisha Igihe cyatakaye",
    sd: "گم ٿيل وقت جي ڳولا ۾",
    si: "නැතිවූ කාලය සෙවීමේදී",
    sk: "Pri hľadaní strateného času",
    sl: "V iskanju izgubljenega časa",
    sm: "I le Sailiga o Taimi Leiloa",
    sn: "Mukutsvaga Nguva Yakarasika",
    so: "Raadinta Waqti Lumay",
    sq: "Në kërkim të kohës së humbur",
    sr: "У потрази за изгубљеним временом",
    st: "Ho Batla Nako e Lahlehileng",
    su: "Dina Milarian Waktu Leungit",
    sv: "På jakt efter den förlorade tiden",
    sw: "Katika Kutafuta Muda Uliopotea",
    ta: "இழந்த நேரத்தைத் தேடி",
    te: "లాస్ట్ టైమ్ శోధనలో",
    tg: "Дар ҷустуҷӯи вақти гумшуда",
    th: "ในการค้นหาเวลาที่หายไป",
    tk: "Ostitirilen wagtyň gözleginde",
    tl: "Sa Paghahanap ng Nawalang Oras",
    tr: "Kayıp Zamanın İzinde",
    tt: "Ostгалтылган вакытны эзләүдә",
    ug: "يوقالغان ۋاقىتنى ئىزدەش",
    uk: "У пошуках втраченого часу",
    ur: "کھوئے ہوئے وقت کی تلاش میں",
    uz: "Yo'qotilgan vaqtni qidirishda",
    vi: "Tìm kiếm thời gian đã mất",
    xh: "Ukukhangela Ixesha Elilahlekileyo",
    yi: "אין זוכן פון פאַרפאַלן צייט",
    yo: "Ni wiwa ti sọnu Time",
    zh: "寻找失去的时间",
    zu: "Ukufuna Isikhathi Esilahlekile",
  }
];
