export const languages = [
  "af",
  "am",
  "ar",
  "az",
  "be",
  "bg",
  "bn",
  "bs",
  "ca",
  "co",
  "cs",
  "cy",
  "da",
  "de",
  "el",
  "en",
  "eo",
  "es",
  "et",
  "eu",
  "fa",
  "fi",
  "fr",
  "fy",
  "ga",
  "gd",
  "gl",
  "gu",
  "ha",
  "he",
  "hi",
  "hr",
  "ht",
  "hu",
  "hy",
  "id",
  "ig",
  "is",
  "it",
  "ja",
  "jv",
  "ka",
  "kk",
  "km",
  "kn",
  "ko",
  "ku",
  "ky",
  "la",
  "lb",
  "lo",
  "lt",
  "lv",
  "mg",
  "mi",
  "mk",
  "ml",
  "mn",
  "mr",
  "ms",
  "mt",
  "my",
  "nb",
  "ne",
  "nl",
  "no",
  "ny",
  "or",
  "pa",
  "pl",
  "ps",
  "pt",
  "ro",
  "ru",
  "rw",
  "sd",
  "si",
  "sk",
  "sl",
  "sm",
  "sn",
  "so",
  "sq",
  "sr",
  "st",
  "su",
  "sv",
  "sw",
  "ta",
  "te",
  "tg",
  "th",
  "tk",
  "tl",
  "tr",
  "tt",
  "ug",
  "uk",
  "ur",
  "uz",
  "vi",
  "xh",
  "yi",
  "yo",
  "zh",
  "zu",
] as const;

// https://docs.google.com/spreadsheets/d/1M9sIYpFBAt1qLJXxbrT-AiMy_xHbq1r_bQux9m49FQQ/edit?usp=sharing
export const multilingualHellos = [
  {
    af: "Hallo",
    am: "ሀሎ",
    ar: "مرحبًا",
    az: "Salam",
    be: "добры дзень",
    bg: "Здравейте",
    bn: "হ্যালো",
    bs: "zdravo",
    ca: "Hola",
    co: "Bonghjornu",
    cs: "Ahoj",
    cy: "Helo",
    da: "Hej",
    de: "Hallo",
    el: "Γειά σου",
    en: "Hello",
    eo: "Saluton",
    es: "Hola",
    et: "Tere",
    eu: "Kaixo",
    fa: "سلام",
    fi: "Hei",
    fr: "Bonjour",
    fy: "Hallo",
    ga: "Dia dhuit",
    gd: "Halò",
    gl: "Ola",
    gu: "નમસ્તે",
    ha: "Sannu",
    he: "שלום",
    hi: "नमस्ते",
    hr: "zdravo",
    ht: "Bonjou",
    hu: "Helló",
    hy: "Բարեւ",
    id: "Halo",
    ig: "Nnọọ",
    is: "Halló",
    it: "Ciao",
    ja: "こんにちは",
    jv: "Halo",
    ka: "გამარჯობა",
    kk: "Сәлеметсіз бе",
    km: "ជំរាបសួរ",
    kn: "ನಮಸ್ಕಾರ",
    ko: "안녕하세요",
    ku: "Slav",
    ky: "Салам",
    la: "Salve",
    lb: "Hallo",
    lo: "ສະບາຍດີ",
    lt: "Sveiki",
    lv: "Sveiki",
    mg: "Salama",
    mi: "Kia ora",
    mk: "Здраво",
    ml: "ഹലോ",
    mn: "Сайн уу",
    mr: "नमस्कार",
    ms: "Hello",
    mt: "Bongu",
    my: "မင်္ဂလာပါ",
    nb: "Hallo",
    ne: "नमस्ते",
    nl: "Hallo",
    no: "Hallo",
    ny: "Moni",
    or: "ନମସ୍କାର",
    pa: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
    pl: "Cześć",
    ps: "سلام",
    pt: "Olá",
    ro: "Buna ziua",
    ru: "Привет",
    rw: "Mwaramutse",
    sd: "سلام",
    si: "ආයුබෝවන්",
    sk: "Ahoj",
    sl: "zdravo",
    sm: "Talofa",
    sn: "Mhoro",
    so: "Hello",
    sq: "Përshëndetje",
    sr: "Здраво",
    st: "Lumela",
    su: "Halo",
    sv: "Hallå",
    sw: "Habari",
    ta: "வணக்கம்",
    te: "హలో",
    tg: "Салом",
    th: "สวัสดี",
    tk: "Salam",
    tl: "Kamusta",
    tr: "Merhaba",
    tt: "Сәлам",
    ug: "ياخشىمۇسىز",
    uk: "Привіт",
    ur: "ہیلو",
    uz: "Salom",
    vi: "Xin chào",
    xh: "Mholo",
    yi: "העלא",
    yo: "Pẹlẹ o",
    zh: "你好",
    zu: "Sawubona",
  },
  {
    af: "Alexander die Grote",
    am: "ታላቁ እስክንድር",
    ar: "الإسكندر الأكبر",
    az: "Makedoniyalı İskəndər",
    be: "Аляксандр Македонскі",
    bg: "Александър Велики",
    bn: "আলেকজান্ডার দ্য গ্রেট",
    bs: "aleksandar veliki",
    ca: "Alexandre el Gran",
    co: "Lisandru Magnu",
    cs: "Alexandr Veliký",
    cy: "Alecsander Fawr",
    da: "Alexander den Store",
    de: "Alexander der Große",
    el: "Μέγας Αλέξανδρος",
    en: "Alexander the Great",
    eo: "Aleksandro la Granda",
    es: "Alejandro el Grande",
    et: "Aleksander Suur",
    eu: "Alexandro Handia",
    fa: "اسکندر کبیر",
    fi: "Aleksanteri Suuri",
    fr: "Alexandre le Grand",
    fy: "Alexander de grutte",
    ga: "Alastar Mór",
    gd: "Alasdair Mòr",
    gl: "Alexandre Magno",
    gu: "મહાન અલેકઝાન્ડર",
    ha: "Alexander the Great",
    he: "אלכסנדר הגדול",
    hi: "सिकंदर महान",
    hr: "Aleksandar Veliki",
    ht: "Aleksann Legran",
    hu: "Nagy Sándor",
    hy: "Ալեքսանդր Մակեդոնացին",
    id: "Alexander yang Agung",
    ig: "Alexander Onye Ukwu",
    is: "Alexander mikli",
    it: "Alessandro Magno",
    ja: "アレキサンダー大王",
    jv: "Alexander Agung",
    ka: "ალექსანდრე დიდი",
    kk: "Александр Македонский",
    km: "លោក Alexander ដ៏​អស្ចារ្យ",
    kn: "ಅಲೆಕ್ಸಾಂಡರ್ ದಿ ಗ್ರೇಟ್",
    ko: "알렉산더 대왕",
    ku: "Îskenderê Mezin",
    ky: "Улуу Александр",
    la: "Alexander Magnus",
    lb: "Alexander de Groussen",
    lo: "Alexander the Great",
    lt: "Aleksandras Didysis",
    lv: "Aleksandrs Lielais",
    mg: "Alexander the Great",
    mi: "Alexander the Great",
    mk: "Александар Велики",
    ml: "മഹാനായ അലക്സാണ്ടർ",
    mn: "Их Александр",
    mr: "अलेक्झांडर द ग्रेट",
    ms: "Alexander the Great",
    mt: "Alessandru l-Kbir",
    my: "မဟာအလက်ဇန်းဒါး",
    nb: "Alexander den store",
    ne: "अलेक्जेन्डर महान्",
    nl: "Alexander de Grote",
    no: "Alexander den store",
    ny: "Alexander Wamkulu",
    or: "ଆଲେକ୍ସଜାଣ୍ଡାର୍ ଦି ଗ୍ରେଟ୍ |",
    pa: "ਸਿਕੰਦਰ ਮਹਾਨ",
    pl: "Aleksander Wielki",
    ps: "سکندر اعظم",
    pt: "Alexandre o grande",
    ro: "Alexandru cel Mare",
    ru: "Александр Великий",
    rw: "Alegizandere Mukuru",
    sd: "سڪندر اعظم",
    si: "මහා ඇලෙක්සැන්ඩර්",
    sk: "Alexander Veľký",
    sl: "Aleksander Veliki",
    sm: "Alesana le Sili",
    sn: "Alexander Mukuru",
    so: "Alexander the Great",
    sq: "Aleksandri i Madh",
    sr: "Александар Велики",
    st: "Alexander e Moholo",
    su: "Alexander Agung",
    sv: "Alexander den store",
    sw: "Alexander Mkuu",
    ta: "மாவீரன் அலெக்ஸ்சாண்டர்",
    te: "అలెగ్జాండర్ ది గ్రేట్",
    tg: "Искандари Мақдунӣ",
    th: "อเล็กซานเดอร์มหาราช",
    tk: "Aleksandr Makedonskiý",
    tl: "Alexander the Great",
    tr: "Büyük İskender",
    tt: "Бөек Александр",
    ug: "ئىسكەندەر زۇلقەرنەيىن",
    uk: "Олександр Великий",
    ur: "سکندر اعظم",
    uz: "Iskandar Zulqarnayn",
    vi: "Alexander vĩ đại",
    xh: "UAlexander Omkhulu",
    yi: "אלעקסאנדער דער גרויסער",
    yo: "Alexander Nla",
    zh: "亚历山大大帝",
    zu: "Alexander Omkhulu",
  },
];
