export const languages = [
  "af",
  "am",
  "ar",
  "az",
  "be",
  "bg",
  "bn",
  "bs",
  "ca",
  "co",
  "cs",
  "cy",
  "da",
  "de",
  "el",
  "en",
  "eo",
  "es",
  "et",
  "eu",
  "fa",
  "fi",
  "fr",
  "fy",
  "ga",
  "gd",
  "gl",
  "gu",
  "ha",
  "he",
  "hi",
  "hr",
  "ht",
  "hu",
  "hy",
  "id",
  "ig",
  "is",
  "it",
  "ja",
  "jv",
  "ka",
  "kk",
  "km",
  "kn",
  "ko",
  "ku",
  "ky",
  "la",
  "lb",
  "lo",
  "lt",
  "lv",
  "mg",
  "mi",
  "mk",
  "ml",
  "mn",
  "mr",
  "ms",
  "mt",
  "my",
  "nb",
  "ne",
  "nl",
  "no",
  "ny",
  "or",
  "pa",
  "pl",
  "ps",
  "pt",
  "ro",
  "ru",
  "rw",
  "sd",
  "si",
  "sk",
  "sl",
  "sm",
  "sn",
  "so",
  "sq",
  "sr",
  "st",
  "su",
  "sv",
  "sw",
  "ta",
  "te",
  "tg",
  "th",
  "tk",
  "tl",
  "tr",
  "tt",
  "ug",
  "uk",
  "ur",
  "uz",
  "vi",
  "xh",
  "yi",
  "yo",
  "zh",
  "zu",
] as const;

// https://docs.google.com/spreadsheets/d/1M9sIYpFBAt1qLJXxbrT-AiMy_xHbq1r_bQux9m49FQQ/edit?usp=sharing
export const multilingualHellos = [
  {
    af: "Alexander die Grote",
    am: "ታላቁ እስክንድር",
    ar: "الإسكندر الأكبر",
    az: "Makedoniyalı İskəndər",
    be: "Аляксандр Македонскі",
    bg: "Александър Велики",
    bn: "আলেকজান্ডার দ্য গ্রেট",
    bs: "aleksandar veliki",
    ca: "Alexandre el Gran",
    co: "Lisandru Magnu",
    cs: "Alexandr Veliký",
    cy: "Alecsander Fawr",
    da: "Alexander den Store",
    de: "Alexander der Große",
    el: "Μέγας Αλέξανδρος",
    en: "Alexander the Great",
    eo: "Aleksandro la Granda",
    es: "Alejandro el Grande",
    et: "Aleksander Suur",
    eu: "Alexandro Handia",
    fa: "اسکندر کبیر",
    fi: "Aleksanteri Suuri",
    fr: "Alexandre le Grand",
    fy: "Alexander de grutte",
    ga: "Alastar Mór",
    gd: "Alasdair Mòr",
    gl: "Alexandre Magno",
    gu: "મહાન અલેકઝાન્ડર",
    ha: "Alexander the Great",
    he: "אלכסנדר הגדול",
    hi: "सिकंदर महान",
    hr: "Aleksandar Veliki",
    ht: "Aleksann Legran",
    hu: "Nagy Sándor",
    hy: "Ալեքսանդր Մակեդոնացին",
    id: "Alexander yang Agung",
    ig: "Alexander Onye Ukwu",
    is: "Alexander mikli",
    it: "Alessandro Magno",
    ja: "アレキサンダー大王",
    jv: "Alexander Agung",
    ka: "ალექსანდრე დიდი",
    kk: "Александр Македонский",
    km: "លោក Alexander ដ៏​អស្ចារ្យ",
    kn: "ಅಲೆಕ್ಸಾಂಡರ್ ದಿ ಗ್ರೇಟ್",
    ko: "알렉산더 대왕",
    ku: "Îskenderê Mezin",
    ky: "Улуу Александр",
    la: "Alexander Magnus",
    lb: "Alexander de Groussen",
    lo: "Alexander the Great",
    lt: "Aleksandras Didysis",
    lv: "Aleksandrs Lielais",
    mg: "Alexander the Great",
    mi: "Alexander the Great",
    mk: "Александар Велики",
    ml: "മഹാനായ അലക്സാണ്ടർ",
    mn: "Их Александр",
    mr: "अलेक्झांडर द ग्रेट",
    ms: "Alexander the Great",
    mt: "Alessandru l-Kbir",
    my: "မဟာအလက်ဇန်းဒါး",
    nb: "Alexander den store",
    ne: "अलेक्जेन्डर महान्",
    nl: "Alexander de Grote",
    no: "Alexander den store",
    ny: "Alexander Wamkulu",
    or: "ଆଲେକ୍ସଜାଣ୍ଡାର୍ ଦି ଗ୍ରେଟ୍ |",
    pa: "ਸਿਕੰਦਰ ਮਹਾਨ",
    pl: "Aleksander Wielki",
    ps: "سکندر اعظم",
    pt: "Alexandre o grande",
    ro: "Alexandru cel Mare",
    ru: "Александр Великий",
    rw: "Alegizandere Mukuru",
    sd: "سڪندر اعظم",
    si: "මහා ඇලෙක්සැන්ඩර්",
    sk: "Alexander Veľký",
    sl: "Aleksander Veliki",
    sm: "Alesana le Sili",
    sn: "Alexander Mukuru",
    so: "Alexander the Great",
    sq: "Aleksandri i Madh",
    sr: "Александар Велики",
    st: "Alexander e Moholo",
    su: "Alexander Agung",
    sv: "Alexander den store",
    sw: "Alexander Mkuu",
    ta: "மாவீரன் அலெக்ஸ்சாண்டர்",
    te: "అలెగ్జాండర్ ది గ్రేట్",
    tg: "Искандари Мақдунӣ",
    th: "อเล็กซานเดอร์มหาราช",
    tk: "Aleksandr Makedonskiý",
    tl: "Alexander the Great",
    tr: "Büyük İskender",
    tt: "Бөек Александр",
    ug: "ئىسكەندەر زۇلقەرنەيىن",
    uk: "Олександр Великий",
    ur: "سکندر اعظم",
    uz: "Iskandar Zulqarnayn",
    vi: "Alexander vĩ đại",
    xh: "UAlexander Omkhulu",
    yi: "אלעקסאנדער דער גרויסער",
    yo: "Alexander Nla",
    zh: "亚历山大大帝",
    zu: "Alexander Omkhulu",
  },
  {
    af: "Verenigde Koninkryk",
    am: "የተባበሩት የንጉሥ ግዛት",
    ar: "المملكة المتحدة",
    az: "Birləşmiş Krallıq",
    be: "Злучанае Каралеўства",
    bg: "Великобритания",
    bn: "যুক্তরাজ্য",
    bs: "ujedinjeno kraljevstvo",
    ca: "Regne Unit",
    co: "Regnu Unitu",
    cs: "Spojené království",
    cy: "Deyrnas Unedig",
    da: "Det Forenede Kongerige",
    de: "Großbritannien",
    el: "Ηνωμένο Βασίλειο",
    en: "United Kingdom",
    eo: "Unuiĝinta Reĝlando",
    es: "Reino Unido",
    et: "Ühendkuningriik",
    eu: "Erresuma Batua",
    fa: "انگلستان",
    fi: "Yhdistynyt kuningaskunta",
    fr: "Royaume-Uni",
    fy: "Feriene Keninkryk",
    ga: "an Ríocht Aontaithe",
    gd: "An Rìoghachd Aonaichte",
    gl: "Reino Unido",
    gu: "યુનાઇટેડ કિંગડમ",
    ha: "Ƙasar Ingila",
    he: "הממלכה המאוחדת",
    hi: "यूनाइटेड किंगडम",
    hr: "Ujedinjeno Kraljevstvo",
    ht: "Wayòm Ini",
    hu: "Egyesült Királyság",
    hy: "Միացյալ թագավորություն",
    id: "Britania Raya",
    ig: "United Kingdom",
    is: "Bretland",
    it: "Regno Unito",
    ja: "イギリス",
    jv: "Inggris",
    ka: "გაერთიანებული სამეფო",
    kk: "Біріккен корольдігі",
    km: "ចក្រភពអង់គ្លេស",
    kn: "ಯುನೈಟೆಡ್ ಕಿಂಗ್ಡಮ್",
    ko: "영국",
    ku: "Inglîz",
    ky: "Бириккен королдук",
    la: "regnum Unitum",
    lb: "Vereenegt Kinnekräich",
    lo: "ສະຫະລາຊະອານາຈັກ",
    lt: "Jungtinė Karalystė",
    lv: "Apvienotā Karaliste",
    mg: "fanjakana mitambatra",
    mi: "United Kingdom",
    mk: "Обединето Кралство",
    ml: "യുണൈറ്റഡ് കിംഗ്ഡം",
    mn: "Их Британи",
    mr: "युनायटेड किंगडम",
    ms: "United Kingdom",
    mt: "Ir-Renju Unit",
    my: "ယူနိုက်တက်ကင်းဒမ်း",
    nb: "Storbritannia",
    ne: "युनाइटेड किंगडम",
    nl: "Verenigd Koninkrijk",
    no: "Storbritannia",
    ny: "United Kingdom",
    or: "ଇଂଗଲାଣ୍ଡ୍",
    pa: "ਯੁਨਾਇਟੇਡ ਕਿਂਗਡਮ",
    pl: "Zjednoczone Królestwo",
    ps: "انګلستان",
    pt: "Reino Unido",
    ro: "Regatul Unit",
    ru: "Великобритания",
    rw: "Ubwongereza",
    sd: "برطانيه",
    si: "එක්සත් රාජධානිය",
    sk: "Spojene kralovstvo",
    sl: "Združeno kraljestvo",
    sm: "Malo tupu",
    sn: "Nyika dzakabatana",
    so: "Boqortooyada Ingiriiska",
    sq: "Mbretëria e Bashkuar",
    sr: "Велика Британија",
    st: "united kingdom",
    su: "karajaan Inggris",
    sv: "Storbritannien",
    sw: "Uingereza",
    ta: "ஐக்கிய இராச்சியம்",
    te: "యునైటెడ్ కింగ్‌డమ్",
    tg: "Инглистон",
    th: "ประเทศอังกฤษ",
    tk: "Angliýa",
    tl: "United Kingdom",
    tr: "Birleşik Krallık",
    tt: "Берләшкән Корольлек",
    ug: "United Kingdom",
    uk: "Об'єднане Королівство",
    ur: "متحدہ سلطنت یونائیٹڈ کنگڈم",
    uz: "Birlashgan Qirollik",
    vi: "Vương quốc Anh",
    xh: "Iunited kingdom",
    yi: "פֿאַראייניקטע מלכות",
    yo: "apapọ ijọba gẹẹsi",
    zh: "英国",
    zu: "i-United Kingdom",
  },
];
